#updated classpath Oct 13, 2023
#Fri Oct 13 17:04:10 UTC 2023
MAIN_CLASS=com.nomagic.magicdraw.commandline.CommandLineActionLauncher
CONSOLE=false
APP_ARGS=
JAVA_HOME=
JAVA_ARGS=-Xmx800M -Dcom.nomagic.magicdraw.commandline.action\=com.nomagic.requirements.reqif.commandline.ReqIFExportCommandLineAction -Desi.system.config\=../data/application.conf -Dfile.encoding\=UTF-8 @../bin/vm.options
MAC_JAVA_ARGS="-Xdock\:name\=ReqIF Command line export" -Xdock\:icon\=../bin/md.icns -Dapple.laf.useScreenMenuBar\=true
CLASSPATH=../lib/brand.jar\:../lib/brand_api.jar\:../lib/classpath.jar
